osx_image: xcode7.2
language: objective-c
xcode_project: Sample/platforms/ios/Sample.xcodeproj # path to your xcodeproj folder
xcode_scheme: SampleTests
branches:
  only:
    - master

script:
- xcodebuild clean build test -scheme SampleTests -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.2' -enableCodeCoverage YES | egrep '^(/.+:[0-9+:[0-9]+:.(error|warning):|fatal|CompileSwift|Test|Build|===)'